### ISSUE TITLE
Add notes to DB schema

### ISSUE THREAD

**Issue by mattwalo32** [hack4impact-uiuc/memberdb-tool#33]
Add a notes section to the Member DB schema.
DB Fields:
- String content
- Metadata
    - String title
    - String[] labels
    - MemberID[] referencedMembers
    - Object[] VersionHistory
        - MemberID actionBy
        - Date date
        - String action (Enum ["CREATE", "EDIT", etc.])
    - Access
        - MemberID[] viewableBy
        - MemberID[] editableBy
        
        
        
Features that notes must have according to [PRD](https://docs.google.com/document/d/1mP3gnZC-b1jFvzx8X62Tq7y4x6jRPuFTHly-pVwRgls/edit#)

- Allow directors to set visibility of note by selecting from list of members
- Track who edited it
- Set scopes of who can view note
- Add titles for notes

**Comment by Qrtn** [comment]
Agreed, notes should be in its own collection. We could just store memberIds in notes, however. Then when querying the notes collection, we can just filter by memberId rather than cross-referencing the two collections.

For flexibility, we may want to have each note contain an array of memberIds to signify which member(s) that note applies to. Or, it could apply to no members at all.

In terms of visibility, we can just have an array of memberIds for each note, containing the ids of members that can view/edit that note. When a lead (for example) queries the DB for notes for a specific member, we filter by `memberId`, then lead's `memberId` "inside" the viewable by members array.

For tracking who edited it: we can opt to store a simple version history, an array of objects containing a memberId and an action. `[{memberId: 1, action: "Created"}, {memberId: 1, action: "Edited"}, {memberId: 4, action: "Edited"}]`

Or, if that's too complex, once any memberId edits/saves the note, we can add that id to an array of members who have edited the doc.

Some additional metadata we may want to store includes: date/time creation, date/time last edited, memberId of creator, date/time last viewed. Note that all of these things can actually be a part of the version history array of objects.
